//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedEasy.DAC {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MedEasySQLCommands {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MedEasySQLCommands() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MedEasy.DAC.MedEasySQLCommands", typeof(MedEasySQLCommands).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT
        ///	ITEM_UID
        ///,ITEM_ID
        ///,ITEM_BRAND_NAME
        ///,ITEM_POWER
        ///,FORM_TYP_UID
        ///,MANUFACTURERS_UID
        ///,PACK_SIZE
        ///,PURCHASE_UNIT
        ///,SALE_UNIT
        ///,NO_OF_UNIT
        ///,PER_UNIT_RATE
        ///,MRP
        ///,MED_TYPE
        ///,SCHEDULE
        ///,RECORDED_QTY
        ///,PROFIT_MERGINE
        ///,CGST
        ///,IGST
        ///,TAX
        ///,DISCOUNT1
        ///,DISCOUNT2
        ///,DISCOUNT3
        ///,STORE_RACK_NO
        ///,STORE_BOX_NO
        ///,DEMAND_GEN_LIMIT
        ///,ORGL_USER
        ///,ORGL_STAMP
        ///,UPDT_USER
        ///,UPDT_STAMP
        ///FROM ME_OWN.MST_ITEM.
        /// </summary>
        internal static string GetItem {
            get {
                return ResourceManager.GetString("GetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select I.ITEM_UID, I.ITEM_BRAND_NAME,SD.BATCH_NO,SD.EXP_DT, SD.PURCHASE_QTY,SD.MRP from ME_OWN.TRN_STOCK_DTL SD
        ///inner join ME_OWN.MST_ITEM I on SD.ITEM_UID = I.ITEM_UID.
        /// </summary>
        internal static string GetStockDtl {
            get {
                return ResourceManager.GetString("GetStockDtl", resourceCulture);
            }
        }
    }
}
